name: ci

env:
  PROJECT_NAME: CppAst

on:
  push:
    branches: [main, master, development]
    tags:
    - '*'
    paths-ignore:
    - 'doc/**'
    - 'img/**'
    - 'readme.md'
  pull_request:

jobs:
  build:
    uses: xoofx/.github/.github/workflows/dotnet.yml@main
    secrets:
      NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}